### PR TITLE
/ ‘Source/bmho/app/Config/bootstrap.php’

### PR DESCRIPTION
**Pull request by memswiler**
/ ‘Source/bmho/app/Config/core.php’
- ‘Source/bmho/app/Controller/CategoriesController.dnd.php’
- ‘Source/bmho/app/Controller/CategoriesController.php’
  / ‘Source/bmho/app/Controller/ProductCategoriesController.php’
- ‘Source/bmho/app/Model/Category.php’
  / ‘Source/bmho/app/Model/ProductCategory.php’
- ‘Source/bmho/app/Plugin/Tools/.coveralls.yml’
- ‘Source/bmho/app/Plugin/Tools/.editorconfig’
- ‘Source/bmho/app/Plugin/Tools/.gitattributes’
  ...

### CODE REVIEW

**Comment by memswiler** [comment]
Please Pull and Merge for latest snapshot

**Comment by odinhaus** [comment]
You already merged it.

Sent from my iPhone

On Aug 9, 2015, at 5:10 PM, memswiler <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #2https://github.com/ByMyHandsOnly/BMHO_Web/pull/2.

**Comment by memswiler** [comment]
Sorry for the confusion ... I meant to merge in your changes down to me, lol

**Comment by odinhaus** [comment]
I have no changes

Sent from my iPhone

On Aug 9, 2015, at 5:45 PM, memswiler <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry for the confusion ... I meant to merge in your changes down to me, lol

**Comment by memswiler** [comment]
There's a whole new folder,  for example, in bmho/app/plugin called Tools
that I just, created, and i thought I saw it in your master tree on the
server!

**Comment by memswiler** [comment]
Oh I misunderstood...  I thought you meant you didn't have my latest
changes,  but meant you had no changes prior to mine,  but github indicated
I was a commit behind,  so I had assumed there were some doc changes.
Likely,  it may have been the previous pull request.  Perhaps I have to
resync my fork after a merge to reach the same commit level in my fork.. I
will give it a look in a bit.  Thanks!

**Comment by odinhaus** [comment]
No problem

Sent from my iPhone

On Aug 9, 2015, at 6:21 PM, memswiler <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh I misunderstood... I thought you meant you didn't have my latest
changes, but meant you had no changes prior to mine, but github indicated
I was a commit behind, so I had assumed there were some doc changes.
Likely, it may have been the previous pull request. Perhaps I have to
resync my fork after a merge to reach the same commit level in my fork.. I
will give it a look in a bit. Thanks!

**Pull request merged**
